baseURL = "http://example.org/"
languageCode = "en-us"
title = "Learning Out Loud"
theme = "cleanwhite"
# Enable comments by entering your Disqus shortname
disqusShortname = ""
googleAnalytics = ""
preserveTaxonomyNames = true
paginate = 5 #frontpage pagination
hasCJKLanguage = true

[outputs]
home = ["HTML"]

[params]
  header_image = "images/header_iwasthinking.jpg"
  
  image_404 = "img/404-bg.jpg"
  omit_categories = false
  

[markup]
  defaultMarkdownHandler = "blackFriday"
  [markup.tableOfContents]
    endLevel = 2
    startLevel = 1
  [markup.highlight]
    style = "dracula"
  [markup.blackFriday]
    angledQuotes = false
    footnoteAnchorPrefix = ""
    footnoteReturnLinkContents = ""
    fractions = true
    hrefTargetBlank = true
    latexDashes = true
    nofollowLinks = false
    noreferrerLinks = false
	skipHTML = false
    smartDashes = true
    smartypants = true
    smartypantsQuotesNBSP = false
    taskLists = true
	